In [172]:
import pandas as pd
import random
import os
import numpy as np
import warnings
warnings.filterwarnings('ignore')

def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
seed_everything(37) # Seed 고정

train_df = pd.read_csv('./train.csv')
test_df = pd.read_csv('./test.csv')

#train_x = train_df.drop(columns=['PRODUCT_ID', 'Y_Class', 'TIMESTAMP'])
train_x = train_df.drop(columns=['PRODUCT_ID', 'Y_Quality', 'TIMESTAMP'])
train_y = train_df['Y_Class']

test_x = test_df.drop(columns=['PRODUCT_ID', 'TIMESTAMP'])

train_x['y0'] = 0
train_x['y1'] = 0
train_x['y2'] = 0
test_x['y0'] = 0
test_x['y1'] = 0
test_x['y2'] = 0


In [173]:
from sklearn.preprocessing import LabelEncoder

qual_col = ['LINE','PRODUCT_CODE']

for i in qual_col:
    le = LabelEncoder()
    le.fit(train_x[i])
    train_x[i] = le.transform(train_x[i])

    for label in np.unique(test_x[i]):
        if label not in le.classes_:
            le.classes_ = np.append(le.classes_, label)
    
    test_x[i] = le.transform(test_x[i])

print('done')

done


In [174]:
## PRODUCT_CODE

# train
train_x_1 = train_x[train_x['PRODUCT_CODE'] == 0]#.drop('Y_Class', axis=1)
train_x_2 = train_x[train_x['PRODUCT_CODE'] == 1]#.drop('Y_Class', axis=1)
train_x_3 = train_x[train_x['PRODUCT_CODE'] == 2]#.drop('Y_Class', axis=1)

train_y_1 = train_x['Y_Class'][train_x['PRODUCT_CODE'] == 0]
train_y_2 = train_x['Y_Class'][train_x['PRODUCT_CODE'] == 1]
train_y_3 = train_x['Y_Class'][train_x['PRODUCT_CODE'] == 2]

print('train_x_1 shape :', train_x_1.shape,
      '\ntrain_x_2 shape :', train_x_2.shape,
      '\ntrain_x_3 shape :', train_x_3.shape)

# test
test_x_1 = test_x[test_x['PRODUCT_CODE'] == 0]
test_x_2 = test_x[test_x['PRODUCT_CODE'] == 1]
test_x_3 = test_x[test_x['PRODUCT_CODE'] == 2]

print('done')

train_x_1 shape : (249, 2881) 
train_x_2 shape : (6, 2881) 
train_x_3 shape : (343, 2881)
done


In [175]:
# LINE

## TRAIN

# line 1
train_x_1_1 = train_x_1[train_x_1['LINE'] == 0]

# line 2
train_x_1_2 = train_x_1[train_x_1['LINE'] == 1]

# line 3
train_x_1_3 = train_x_1[train_x_1['LINE'] == 2]

# line 4
train_x_1_4 = train_x_1[train_x_1['LINE'] == 3]

# line 5
train_x_2_5 = train_x_2[train_x_2['LINE'] == 4]
train_x_3_5 = train_x_3[train_x_3['LINE'] == 4]

# line 6
train_x_2_6 = train_x_2[train_x_2['LINE'] == 5]
train_x_3_6 = train_x_3[train_x_3['LINE'] == 5]

train_set = [train_x_1_1, train_x_1_2, train_x_1_3, train_x_1_4, train_x_2_5, train_x_3_5, train_x_2_6, train_x_3_6]

for set in train_set:
    print(set.shape)

(59, 2881)
(70, 2881)
(78, 2881)
(42, 2881)
(3, 2881)
(172, 2881)
(3, 2881)
(171, 2881)


In [176]:
## TEST

# line 1
test_x_1_1 = test_x_1[test_x_1['LINE'] == 0]

# line 2
test_x_1_2 = test_x_1[test_x_1['LINE'] == 1]

# line 3
test_x_1_3 = test_x_1[test_x_1['LINE'] == 2]

# line 4
test_x_1_4 = test_x_1[test_x_1['LINE'] == 3]

# line 5
test_x_2_5 = test_x_2[test_x_2['LINE'] == 4]
test_x_3_5 = test_x_3[test_x_3['LINE'] == 4]

# line 6
test_x_2_6 = test_x_2[test_x_2['LINE'] == 5]
test_x_3_6 = test_x_3[test_x_3['LINE'] == 5]

test_set = [test_x_1_1, test_x_1_2, test_x_1_3, test_x_1_4, test_x_2_5, test_x_3_5, test_x_2_6, test_x_3_6]

for set in test_set:
    print(set.shape)

(14, 2880)
(14, 2880)
(13, 2880)
(26, 2880)
(3, 2880)
(108, 2880)
(1, 2880)
(131, 2880)


In [179]:
test_x_1_1

LINE  PRODUCT_CODE  X_1  X_2  X_3  X_4  X_5  X_6  X_7  X_8  ...  X_2869  \
3       0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
6       0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
10      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
11      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
38      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
40      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
71      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
86      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
88      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
89      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
116     0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
117     0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
141     0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
142     0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   

     X_2870  X_2871  X_2872  X_2873  X_2874  X_2875        y0       y1  \
3       NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
6       NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
10      NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
11      NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
38      NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
40      NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
71      NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
86      NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
88      NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
89      NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
116     NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
117     NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
141     NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   
142     NaN     NaN     NaN     NaN     NaN     NaN  0.220339  0.59322   

           y2  
3    0.186441  
6    0.186441  
10   0.186441  
11   0.186441  
38   0.186441  
40   0.186441  
71   0.186441  
86   0.186441  
88   0.186441  
89   0.186441  
116  0.186441  
117  0.186441  
141  0.186441  
142  0.186441  

[14 rows x 2880 columns]

In [177]:
for idx, set in enumerate(train_set):
    sum = set['Y_Class'].value_counts().sum()
    y_value = set['Y_Class'].value_counts()
    per = (y_value/sum).sort_index()
    
    set['y0'] = per[0]
    set['y1'] = per[1]
    set['y2'] = per[2]
    
    test_set[idx]['y0'] = per[0]
    test_set[idx]['y1'] = per[1]
    test_set[idx]['y2'] = per[2]



    #for idx, p in enumerate(per):
        #set['y0'][set['Y_Class']==idx] = p





test_set = [test_x_1_1, test_x_1_2, test_x_1_3, test_x_1_4, test_x_2_5, test_x_3_5, test_x_2_6, test_x_3_6]
train_set = [train_x_1_1, train_x_1_2, train_x_1_3, train_x_1_4, train_x_2_5, train_x_3_5, train_x_2_6, train_x_3_6]

KeyError: 0

In [163]:
test_x_1_1

LINE  PRODUCT_CODE  X_1  X_2  X_3  X_4  X_5  X_6  X_7  X_8  ...  X_2867  \
3       0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
6       0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
10      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
11      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
38      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
40      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
71      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
86      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
88      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
89      0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
116     0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
117     0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
141     0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   
142     0             0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...     NaN   

     X_2868  X_2869  X_2870  X_2871  X_2872  X_2873  X_2874  X_2875  y_per  
3       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
6       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
10      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
11      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
38      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
40      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
71      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
86      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
88      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
89      NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
116     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
117     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
141     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  
142     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      0  

[14 rows x 2878 columns]

In [ ]:
for idx, set in enumerate(train_set):
    set.drop('Y_Class', axis=1, inplace=True)




test_set = [test_x_1_1, test_x_1_2, test_x_1_3, test_x_1_4, test_x_2_5, test_x_3_5, test_x_2_6, test_x_3_6]
train_set = [train_x_1_1, train_x_1_2, train_x_1_3, train_x_1_4, train_x_2_5, train_x_3_5, train_x_2_6, train_x_3_6]

In [149]:
train_x = pd.concat(train_set, axis=0).sort_index()

train_x.shape

(598, 2878)

In [150]:
from sklearn.model_selection import train_test_split

x_t, x_v, y_t, y_v = train_test_split(train_x, train_y, test_size=0.2, random_state=42)

In [151]:
from xgboost import XGBClassifier # 회귀트리

xgb = XGBClassifier()
xgb.fit(x_t, y_t)
pred = xgb.predict(x_v)

from sklearn.metrics import accuracy_score, confusion_matrix

print(accuracy_score(pred, y_v))
print(confusion_matrix(pred, y_v))

0.95
[[21  0  2]
 [ 0 76  2]
 [ 2  0 17]]


In [153]:
from xgboost import XGBClassifier # 회귀트리

xgb = XGBClassifier()
xgb.fit(train_x, train_y)
pred = xgb.predict(test_x)


submit_csv = pd.read_csv('./sample_submission.csv')
submit_csv['Y_Class'] = pred
submit_csv.to_csv('XGBoost_null_submission.csv', index=False)

ValueError: Feature shape mismatch, expected: 2878, got 2877